/*
 * File: app/controller/LoginController.js
 * 
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 * 
 * This file requires use of the Ext JS 4.1.x library, under independent
 * license. License of Sencha Architect does not include license for Ext JS
 * 4.1.x. For more details see http://www.sencha.com/license or contact
 * license@sencha.com.
 * 
 * This file will be auto-generated each and everytime you save your project.
 * 
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.LoginController', {
			extend : 'Ext.app.Controller',

			stores : ['UserJsonStore'],

			onLoginButtonClick : function(button, e, options) {
				console.log("Show LoginWindow");
				Ext.create('MyApp.view.LoginWindow').show();
			},

			onDoLoginButtonClick : function(button, e, options) {
				console.log("Do Login!!!");

				var window = Ext.getCmp('LoginWindow'), userName = window
						.getComponent('UserNameTextField').getValue(), pass = window
						.getComponent('PasswordTextField').getValue();

				record = Ext.create('MyApp.model.UserModel');
				record.set('UserName', userName);
				record.set('Pass', pass);

				console.log(record.get('UserName'));

				//var store = Ext.create('MyApp.store.UserJsonStore');
				// store.load();
				//record.save();

				// Ext.util.JSON.
				Ext.Ajax.request({
							url : 'doLogin2.action', // where you wanna post
							params : userName, // your json data
							params : pass,
							success : function(response) {
								var text = response.responseText;
								console.log("response: " + text);
							}
						});
				Ext.Ajax.request({
							url : 'doLoginWrapper.action', // where you wanna post
							type : 'json',
							encode : true,
							model : 'UserModel',
							params : record, // your json data
							success : function(response) {
								var text = response.responseText;
								console.log("response: " + text);
							}
						});
						
				Ext.Ajax.request({
							url : 'doLoginUser.action', // where you wanna post
							type : 'json',
							encode : false,
							model : 'UserModel',
							params : record, // your json data
							success : function(response) {
								var text = response.responseText;
								console.log("response: " + text);
							}
						});

				Ext.Ajax.request({
							url : 'doLogin.action', // where you wanna post
							type : 'json',
							encode : false,
							model : 'UserModel',
							params : record, // your json data
							success : function(response) {
								var text = response.responseText;
								console.log("response: " + text);
							}
						});

				window.close();
			},

			init : function(application) {
				this.control({
							"button#LoginButton" : {
								click : this.onLoginButtonClick
							},
							"button#DoLoginButton" : {
								click : this.onDoLoginButtonClick
							}
						});
			}

		});
